### ISSUE TITLE
Best working strategy

### ISSUE THREAD

**Issue by Virviil** [BucklerBot/buckler#1]
Please, leave in the comments best working strategy for the bot.

**Comment by ghost** [comment]
I think instead of using a handle for the chat itself, you should make a helper channel with given handle where the user is asked to talk to the bot. The bot, then, replies with captcha. If the captcha reply is correct then the user is added. Maximum amount of failures should be 3 per 24h.

**Comment by couchemar** [comment]
I agree with @fwrs.

If this is not an option we can create more tolerant bot, which does not delete messages immediately but keep them for some amount of time.

**Comment by szobov** [comment]
@fwrs I'm not sure about this idea, because one spam-bot can make a lot of noise in group chat.
I suppose that good idea is give to user only one chance to input correct captcha.
But admins of group should leave information about that behavior and write their contacts for unblocked wrongly banned users.

Or it's should be configurable option.

**Comment by Virviil** [comment]
Lets try to do tolerant bot - then we'll collect user expirience

**Comment by Virviil** [comment]
Resolved in https://github.com/BucklerBot/buckler/pull/7/commits/1fa1665c13452e7c1c800978767e307773b7c0d0
